on:
  push:
    branches:
    - zola
    
name: Build Github Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: shalzz/zola-deploy-action@v0.16.1-1 
      env:
        PAGES_BRANCH: master
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
